version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ilham
      POSTGRES_PASSWORD: ilham
      POSTGRES_SCHEMA: ilham
      POSTGRES_DB: ilham
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - localhost
    restart: unless-stopped

networks:
  localhost:
    driver: bridge

volumes:
    postgres:
    